[workspace]
members = [ "crates/*" ]
default-members = [ "crates/web" ]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0 OR MIT"
version = "0.2.0-pre"

[workspace.dependencies]
serde =  "1.0.188"
