[package]
name = "coach"

version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# internal
engine = { path = "../engine" }
# external
rayon = "1.8.0"
serde = { workspace = true, features = ["derive"] }
csv = "1.3.0"
