[package]
name = "web"

version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "server"

[dependencies]
# internal
engine = { path = "../engine" }
logic = { path = "../logic" }
# external
axum = "0.6.20"
hyper = "0.14.27"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
shuttle-axum = "0.29.0"
shuttle-runtime = "0.29.0"
tokio = { version = "1.33.0", features = ["full"] }
tower = "0.4.13"
utoipa = { workspace = true, features = ["axum_extras", "preserve_order"] }
utoipa-swagger-ui = { version = "4.0.0", features = ["axum"] }
