[package]
name = "wildbg-c"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[lib]
name = "wildbg"
crate-type = ["staticlib"]

[dependencies]
# internal
logic = { path = "../logic" }
